// Mocks generated by Mockito 5.4.6 from annotations
// in modern_turkmen_admin/test/data/repositories/auth/auth_repository_firebase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:modern_turkmen_admin/data/services/auth_service.dart' as _i4;
import 'package:modern_turkmen_admin/data/services/firestore/firestore_service.dart'
    as _i6;
import 'package:modern_turkmen_admin/data/services/firestore/model/exercise/exercise_firestore_model.dart'
    as _i7;
import 'package:modern_turkmen_admin/data/services/firestore/model/tutorial/tutorial_firestore_model.dart'
    as _i3;
import 'package:modern_turkmen_admin/domain/models/user/user.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTutorialFirestoreModel_1 extends _i1.SmartFake
    implements _i3.TutorialFirestoreModel {
  _FakeTutorialFirestoreModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> signInWithEmailAndPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i6.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.User> getUser(String? currentUserId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [currentUserId],
        ),
        returnValue: _i5.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUser,
            [currentUserId],
          ),
        )),
      ) as _i5.Future<_i2.User>);

  @override
  _i5.Stream<List<_i3.TutorialFirestoreModel>> getTutorialsStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTutorialsStream,
          [],
        ),
        returnValue: _i5.Stream<List<_i3.TutorialFirestoreModel>>.empty(),
      ) as _i5.Stream<List<_i3.TutorialFirestoreModel>>);

  @override
  _i5.Stream<List<_i7.ExerciseFirestoreModel>> getExercisesStream(
    String? tutorialId,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercisesStream,
          [
            tutorialId,
            languageCode,
          ],
        ),
        returnValue: _i5.Stream<List<_i7.ExerciseFirestoreModel>>.empty(),
      ) as _i5.Stream<List<_i7.ExerciseFirestoreModel>>);

  @override
  _i5.Future<_i7.ExerciseFirestoreModel?> getExercise(
    String? tutorialId,
    String? languageCode,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercise,
          [
            tutorialId,
            languageCode,
            exerciseId,
          ],
        ),
        returnValue: _i5.Future<_i7.ExerciseFirestoreModel?>.value(),
      ) as _i5.Future<_i7.ExerciseFirestoreModel?>);

  @override
  _i5.Future<_i3.TutorialFirestoreModel> getTutorial(String? tutorialId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTutorial,
          [tutorialId],
        ),
        returnValue: _i5.Future<_i3.TutorialFirestoreModel>.value(
            _FakeTutorialFirestoreModel_1(
          this,
          Invocation.method(
            #getTutorial,
            [tutorialId],
          ),
        )),
      ) as _i5.Future<_i3.TutorialFirestoreModel>);

  @override
  _i5.Future<void> createExercise(
    String? tutorialId,
    String? languageCode,
    _i7.ExerciseFirestoreModel? exercise,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [
            tutorialId,
            languageCode,
            exercise,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateExercise(
    String? tutorialId,
    String? languageCode,
    _i7.ExerciseFirestoreModel? exercise,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [
            tutorialId,
            languageCode,
            exercise,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.ExerciseFirestoreModel>> getExercises(
    String? tutorialId,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [
            tutorialId,
            languageCode,
          ],
        ),
        returnValue: _i5.Future<List<_i7.ExerciseFirestoreModel>>.value(
            <_i7.ExerciseFirestoreModel>[]),
      ) as _i5.Future<List<_i7.ExerciseFirestoreModel>>);

  @override
  _i5.Future<void> deleteExercise(
    String? tutorialId,
    String? languageCode,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            tutorialId,
            languageCode,
            exerciseId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> addTutorial(_i3.TutorialFirestoreModel? tutorial) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTutorial,
          [tutorial],
        ),
        returnValue: _i5.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #addTutorial,
            [tutorial],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> updateTutorial(_i3.TutorialFirestoreModel? tutorial) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTutorial,
          [tutorial],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteTutorial(String? tutorialId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTutorial,
          [tutorialId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
