// Mocks generated by Mockito 5.4.6 from annotations
// in modern_turkmen_admin/test/ui/core/view_model/dropzone_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i10;

import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter_dropzone/src/dropzone_view.dart' as _i2;
import 'package:flutter_dropzone_platform_interface/flutter_dropzone_platform_interface.dart'
    as _i8;
import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:modern_turkmen_admin/data/repositories/auth/auth_repository.dart'
    as _i7;
import 'package:modern_turkmen_admin/data/repositories/file/file_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDropzoneView_0 extends _i1.SmartFake implements _i2.DropzoneView {
  _FakeDropzoneView_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeDateTime_1 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFileRepository extends _i1.Mock implements _i4.FileRepository {
  MockFileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> uploadFile(
    dynamic localFileName,
    dynamic bytes,
    String? userId,
    dynamic Function(
      String,
      String?,
    )? onFileUploaded,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            localFileName,
            bytes,
            userId,
            onFileUploaded,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i6.XFile>?> pickFiles(
    List<String>? mime,
    bool? multiple,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickFiles,
          [
            mime,
            multiple,
          ],
        ),
        returnValue: _i5.Future<List<_i6.XFile>?>.value(),
      ) as _i5.Future<List<_i6.XFile>?>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i7.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DropzoneViewController].
///
/// See the documentation for Mockito's code generation for more information.
class MockDropzoneViewController extends _i1.Mock
    implements _i2.DropzoneViewController {
  MockDropzoneViewController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get viewId => (super.noSuchMethod(
        Invocation.getter(#viewId),
        returnValue: 0,
      ) as int);

  @override
  _i2.DropzoneView get widget => (super.noSuchMethod(
        Invocation.getter(#widget),
        returnValue: _FakeDropzoneView_0(
          this,
          Invocation.getter(#widget),
        ),
      ) as _i2.DropzoneView);

  @override
  _i5.Future<bool> setOperation(_i8.DragOperation? operation) =>
      (super.noSuchMethod(
        Invocation.method(
          #setOperation,
          [operation],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setCursor(_i8.CursorType? cursor) => (super.noSuchMethod(
        Invocation.method(
          #setCursor,
          [cursor],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> setMIME(List<String>? mimes) => (super.noSuchMethod(
        Invocation.method(
          #setMIME,
          [mimes],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<dynamic>> pickFiles({
    bool? multiple = false,
    List<String>? mime = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickFiles,
          [],
          {
            #multiple: multiple,
            #mime: mime,
          },
        ),
        returnValue: _i5.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i5.Future<List<dynamic>>);

  @override
  _i5.Future<String> getFilename(dynamic htmlFile) => (super.noSuchMethod(
        Invocation.method(
          #getFilename,
          [htmlFile],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getFilename,
            [htmlFile],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<int> getFileSize(dynamic htmlFile) => (super.noSuchMethod(
        Invocation.method(
          #getFileSize,
          [htmlFile],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> getFileMIME(dynamic htmlFile) => (super.noSuchMethod(
        Invocation.method(
          #getFileMIME,
          [htmlFile],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #getFileMIME,
            [htmlFile],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<DateTime> getFileLastModified(dynamic htmlFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileLastModified,
          [htmlFile],
        ),
        returnValue: _i5.Future<DateTime>.value(_FakeDateTime_1(
          this,
          Invocation.method(
            #getFileLastModified,
            [htmlFile],
          ),
        )),
      ) as _i5.Future<DateTime>);

  @override
  _i5.Future<String> createFileUrl(dynamic htmlFile) => (super.noSuchMethod(
        Invocation.method(
          #createFileUrl,
          [htmlFile],
        ),
        returnValue: _i5.Future<String>.value(_i9.dummyValue<String>(
          this,
          Invocation.method(
            #createFileUrl,
            [htmlFile],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<bool> releaseFileUrl(String? fileUrl) => (super.noSuchMethod(
        Invocation.method(
          #releaseFileUrl,
          [fileUrl],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i10.Uint8List> getFileData(dynamic htmlFile) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileData,
          [htmlFile],
        ),
        returnValue: _i5.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
      ) as _i5.Future<_i10.Uint8List>);

  @override
  _i5.Stream<List<int>> getFileStream(dynamic htmlFile) => (super.noSuchMethod(
        Invocation.method(
          #getFileStream,
          [htmlFile],
        ),
        returnValue: _i5.Stream<List<int>>.empty(),
      ) as _i5.Stream<List<int>>);
}
