// Mocks generated by Mockito 5.4.6 from annotations
// in modern_turkmen_admin/test/data/repositories/file/file_repository_storage_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:image_picker/image_picker.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:modern_turkmen_admin/data/services/firebase_storage_service.dart'
    as _i2;
import 'package:modern_turkmen_admin/data/services/image_picker_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FirebaseStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorageService extends _i1.Mock
    implements _i2.FirebaseStorageService {
  MockFirebaseStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> uploadFile(
    String? localFileName,
    _i4.Uint8List? bytes,
    String? userId,
    dynamic Function(
      String,
      String?,
    )? onFileUploaded,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [
            localFileName,
            bytes,
            userId,
            onFileUploaded,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> fileExists(String? file) => (super.noSuchMethod(
        Invocation.method(
          #fileExists,
          [file],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [ImagePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePickerService extends _i1.Mock
    implements _i5.ImagePickerService {
  MockImagePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i6.XFile>?> pickFile(
    List<String>? mime,
    bool? multiple,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickFile,
          [
            mime,
            multiple,
          ],
        ),
        returnValue: _i3.Future<List<_i6.XFile>?>.value(),
      ) as _i3.Future<List<_i6.XFile>?>);
}
