// Mocks generated by Mockito 5.4.6 from annotations
// in modern_turkmen_admin/test/ui/exercises/view_model/exercises_list_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:modern_turkmen_admin/data/repositories/exercise/exercise_repository.dart'
    as _i6;
import 'package:modern_turkmen_admin/data/repositories/tutorial/tutorial_repository.dart'
    as _i3;
import 'package:modern_turkmen_admin/domain/models/exercise/exercise.dart'
    as _i7;
import 'package:modern_turkmen_admin/domain/models/tutorial/tutorial.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTutorial_0 extends _i1.SmartFake implements _i2.Tutorial {
  _FakeTutorial_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TutorialRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTutorialRepository extends _i1.Mock
    implements _i3.TutorialRepository {
  MockTutorialRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Tutorial> getTutorial(String? tutorialId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTutorial,
          [tutorialId],
        ),
        returnValue: _i4.Future<_i2.Tutorial>.value(_FakeTutorial_0(
          this,
          Invocation.method(
            #getTutorial,
            [tutorialId],
          ),
        )),
      ) as _i4.Future<_i2.Tutorial>);

  @override
  _i4.Future<String> addTutorial(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTutorial,
          [data],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #addTutorial,
            [data],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateTutorial(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTutorial,
          [data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<List<_i2.Tutorial>> getTutorialsStream() => (super.noSuchMethod(
        Invocation.method(
          #getTutorialsStream,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.Tutorial>>.empty(),
      ) as _i4.Stream<List<_i2.Tutorial>>);

  @override
  _i4.Future<void> deleteTutorial(String? tutorialId) => (super.noSuchMethod(
        Invocation.method(
          #deleteTutorial,
          [tutorialId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ExerciseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExerciseRepository extends _i1.Mock
    implements _i6.ExerciseRepository {
  MockExerciseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FutureOr<_i7.Exercise?> getExercise(
    String? tutorialId,
    String? languageCode,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getExercise,
        [
          tutorialId,
          languageCode,
          exerciseId,
        ],
      )) as _i4.FutureOr<_i7.Exercise?>);

  @override
  _i4.Future<void> createExercise(
    String? tutorialId,
    String? languageCode,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createExercise,
          [
            tutorialId,
            languageCode,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateExercise(
    String? tutorialId,
    String? languageCode,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateExercise,
          [
            tutorialId,
            languageCode,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Exercise>> getExercises(
    String? tutorialId,
    String? languageCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExercises,
          [
            tutorialId,
            languageCode,
          ],
        ),
        returnValue: _i4.Future<List<_i7.Exercise>>.value(<_i7.Exercise>[]),
      ) as _i4.Future<List<_i7.Exercise>>);

  @override
  _i4.Future<void> deleteExercise(
    String? tutorialId,
    String? languageCode,
    String? exerciseId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteExercise,
          [
            tutorialId,
            languageCode,
            exerciseId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
